# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First Name')),
                ('last_name', models.FloatField(verbose_name='Last Name')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
    ]
