# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_accounts',
            name='FA_name',
            field=models.CharField(max_length=120, verbose_name='Fee Name'),
        ),
        migrations.AlterField(
            model_name='fees_accounts',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
