# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SHS_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SHS_subjectName', models.CharField(max_length=120, verbose_name='Subject Name')),
                ('SHS_desc', models.CharField(max_length=12, verbose_name='Description')),
                ('SHS_trackStatus', models.IntegerField()),
            ],
        ),
    ]
